# Generated by Django 4.1.6 on 2023-02-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_author_article_author_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author_a',
            new_name='author',
        ),
    ]
